name: Zip and Upload to AWS S3

on:
  push:
    branches: [main]

env:
  AWS_REGION: "us-east-1"
  S3_BUCKET: "wavewise"

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from IAM role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::851725484938:role/aws-github
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsDeploymentSession

      - name: Zip project directory
        run: zip -r wavewise-backend.zip .

      - name: Upload zip to S3
        run: aws s3 cp wavewise-backend.zip s3://${{ env.S3_BUCKET }}/wavewise-backend.zip

      - name: Cleanup local zip file
        run: rm wavewise-backend.zip
