name: Zip and Update Lambda Function

on:
  push:
    branches: [main]

env:
  AWS_REGION: "us-east-1"
  S3_BUCKET: "wavewise"
  LAMBDA_FUNCTION_NAME: "wavewise-backend"

jobs:
  deploy:
    name: Deploy to S3 and Update Lambda Function
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node.js version

      - name: Install production dependencies with Yarn
        run: yarn install --production

      - name: Bundle Lambda function
        run: npx esbuild index.js --bundle --platform=node --target=node16 --outfile=bundle.js
        # Adjust the entry file and esbuild options as needed

      - name: Zip bundled Lambda function
        run: zip -r lambda.zip bundle.js node_modules

      - name: Upload zip to S3
        run: aws s3 cp lambda.zip s3://${{ env.S3_BUCKET }}/${{ env.LAMBDA_FUNCTION_NAME }}.zip

      - name: Update Lambda function code from S3
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --s3-key ${{ env.LAMBDA_FUNCTION_NAME }}.zip
